In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier, HistGradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, precision_score, recall_score
import warnings
warnings.filterwarnings("ignore")

In [2]:
X, y = load_breast_cancer(return_X_y=True, as_frame=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

models = [
    LogisticRegression(),
    RidgeClassifier(),
    SVC(),
    KNeighborsClassifier(),
    GaussianNB(),
    DecisionTreeClassifier(),
    ExtraTreeClassifier(),
    RandomForestClassifier(),
    ExtraTreesClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier(),
    HistGradientBoostingClassifier(),
    XGBClassifier(n_estimators=100),
    LGBMClassifier(n_estimators=100, verbosity=-1),
    CatBoostClassifier(iterations=100, logging_level='Silent'),
]
submissions = []
scores = []

for model in models:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    submissions.append(y_pred)
    scores.append(accuracy_score(y_test, y_pred))

In [3]:
from dm_utils.utils.submit import cmp_classification

names = ['lr', 'ridge', 'svm', 'knn', 'nb', 'dt', 'et', 'rf', 'ets', 'ada', 'gb', 'hgb', 'xgb', 'lgb', 'cb']
res_cmp_sub = cmp_classification(submissions, scores, names=names, score_func=accuracy_score)

In [4]:
res_cmp_sub = cmp_classification(submissions, scores, names=names, score_func=f1_score)